### ISSUE TITLE
[VSCode] Allow initiation of a Codio recording via a command

### ISSUE THREAD

**Issue by bradydowling** [wix-incubator/codio#30]
Users should be able to:
1. Open the command palette/use a keybinding to _start_ recording a Codio
1. Open the command palette/use a keybinding to _stop_ recording a Codio

**Comment by bogobogo** [comment]
@bradydowling This is already implemented, as you can see [here](https://github.com/wix-incubator/codio/blob/master/vscode/package.json#L51) and [here](https://github.com/wix-incubator/codio/blob/master/vscode/package.json#L70). Let me know if there is anything else we can do to clarify it etc, and if not I will close the issue.

**Comment by bradydowling** [comment]
Oh great! My mistake, feel free to close this!

**Comment by bradydowling** [comment]
I actually don't see any of these commands when I open up the command palette in VSCode. Are you able to see them @bogobogo?

**Comment by bogobogo** [comment]
@bradydowling I am going to go over all the issues and the PR's later today and update you.

**Comment by bogobogo** [comment]
@bradydowling I am seeing those commands, just verified after a fresh install. 
I am opening the command palette with cmd + shift +p, and after  typing "codio" all the commands show up. Does this happen to you on macOS, Windows or both?

**Comment by bradydowling** [comment]
I'm on mac but a reinstall fixed it. If it happens again I'll troubleshoot it.
