### ISSUE TITLE
Is this project still working?

### ISSUE THREAD

**Issue by fetsorn** [wix-incubator/codio#69]
I installed the VSCode extension and added it to the project but "Record Codio" did not show any activity. Is this known to be broken or an issue on my end?

**Comment by bogobogo** [comment]
Hey @fetsorn ! Are you using mac or windows (or linux)? I will take a look. 

The project is currently not actively maintained (though I do hope to get back to it at some point) but there is a relatively active fork here: https://github.com/rbrisita/codio-sui 

@rbrisita is doing cool work there, so I think I will add a comment to the readme until I get back to it

**Comment by fetsorn** [comment]
I used Visual Studio Code on MacOS Monterey 12.1, MacBook Air M1 2020.
After installing rbrisita's fork with a .vsix I get the following error: "Codio could not find an audio recording device."
Opened an issue there, https://github.com/rbrisita/codio-sui/issues/107

**Comment by fetsorn** [comment]
The issue was resolved after I installed a version of ffmpeg that supports avfoundation.
To check if your ffmpeg supports it, run 
`ffmpeg -hide_banner -nostats -f avfoundation -list_devices true -i ""`

**Comment by bogobogo** [comment]
@fetsorn Awesome, any other feedback on the project (either here on or in the fork) is more than welcome!
