### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by mavrk-mose** [wix-incubator/codio#70]
- Issue Type: `Bug`
- Extension Name: `codio`
- Extension Version: `0.1.13`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by bogobogo** [comment]
Hey @mavrk-mose , I am not sure what the issue is...
